# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='category',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='picture',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
