# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170314_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
