# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.FileField(null=True, upload_to='polls'),
        ),
    ]
