# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170316_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.CharField(default='polls/static/', help_text='input filename.type', max_length=60),
        ),
    ]
