# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 21:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170316_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/polls'), upload_to=''),
        ),
    ]
